/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dromara_jdlib_Jdlib */

#ifndef _Included_org_dromara_jdlib_Jdlib
#define _Included_org_dromara_jdlib_Jdlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dromara_jdlib_Jdlib
 * Method:    getFaceDectorHandler
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dromara_jdlib_Jdlib_getFaceDectorHandler
  (JNIEnv *, jobject);

/*
 * Class:     org_dromara_jdlib_Jdlib
 * Method:    getShapePredictorHandler
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_dromara_jdlib_Jdlib_getShapePredictorHandler
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_dromara_jdlib_Jdlib
 * Method:    getFaceEmbeddingHandler
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_dromara_jdlib_Jdlib_getFaceEmbeddingHandler
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_dromara_jdlib_Jdlib
 * Method:    faceDetect
 * Signature: (J[BII)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_org_dromara_jdlib_Jdlib_faceDetect
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_dromara_jdlib_Jdlib
 * Method:    getFacialLandmarks
 * Signature: (JJ[BII)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_org_dromara_jdlib_Jdlib_getFacialLandmarks
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_dromara_jdlib_Jdlib
 * Method:    getFaceEmbeddings
 * Signature: (JJJ[BII)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_org_dromara_jdlib_Jdlib_getFaceEmbeddings
  (JNIEnv *, jobject, jlong, jlong, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
